### ISSUE TITLE
DllNotFoundException: RakNet

### ISSUE THREAD

**Issue by srfoster** [noblewhale/NATPunchthroughClient#2]
Hi,

I'm using this (via the Unity Asset Store).  It gives me a DllNotFoundException for RakNet.  Is this something that could be fixed by compiling RakNet for Mac?  Or is that a dead end?  Or am I doing something else wrong?

--Stephen

**Comment by AnsonKindred** [comment]
Yeah, it sounds like the RakNet library needs to be compiled specifically
for mac. You might be able to try fiddling with the import settings on the
RakNet.so files but I'm not too optimistic that it will help, I just
noticed that the OS is set to Linux for the .so files so maybe setting it
to Mac will help. I'll see if I can get my hands on a mac so I can compile
the libraries and update the plugin. In the meantime if you manage to
compile it yourself I would really appreciate it if you could send me the
compiled library and save me a step :)

I apologize if I wasn't clear about mac compatibility on the asset store
page, I would totally understand if you want a refund since it doesn't
actually work on mac as is, but I'll be working to update it as soon as
possible.

I'll keep you up to date. Let me know if you make any progress compiling
RakNet for Mac.

**Comment by AnsonKindred** [comment]
Hi again,

I just finally got the RakNet library compiled for mac. Sorry it took so
long. I'm packaging the update right now. It will be available in 5-10
days. I can also send you over the mac library right now so you can drop it
into your project if you'd like, just let me know.

Thanks for your patience,
Zeb

**Comment by srfoster** [comment]
Just wanted to let you know that I finally circled back today and was able to use this successfully on a Mac.  Works like a charm.

**Comment by AnsonKindred** [comment]
Awesome, that's great to hear. Let me know if you run into any other issues. Also if you have not yet rated / reviewed the asset on the asset store I would really appreciate it.

Thanks!

**Comment by srfoster** [comment]
Thanks.  I submitted one just now.
